### ISSUE TITLE
Jupter Lab Instance

### ISSUE THREAD

**Issue by BradyPlanden** [galv-team/galv-frontend#16]
**Describe the solution you'd like**
A request from the Oslo workshop:

"Can a jupyter lab instance be hosted alongside the galv frontend with a button to export data into the notebook instead of the example scripts"

**Comment by mjaquiery** [comment]
Good question. Do you know offhand what this might involve? We're presumably loth to provide unlimited computational resources to people - can we provide a Jupyter instance in a way that isn't costly? We could write a nicer Python API and offer it on PyPI. A fairly significant undertaking, but would essentially be a wrapper to the existing API that provided a cleaner interface - e.g. allowing you to download anything and its related resources via its UUID.

**Comment by mjaquiery** [comment]
We can do this through the magic of Web Assembly. Instead of hosting a JupyterLab instance where we have to provide computational resources for users, we can spin up [our own instance of JupyterLite](https://github.com/galv-team/jupyterlite/). 

JupyterLite is an instance of Jupyter compiled to WASM, meaning it runs entirely on the user's computer.

**Comment by BradyPlanden** [comment]
That's brilliant, nice one!
